---
name: flutter_music_player_desk_web
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.3
  desktop_window: ^0.4.0
  flutter:
    sdk: flutter
  provider: ^5.0.0
dev_dependencies:
  dart_code_metrics: null
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  fonts:
  - family: Montserrat
    fonts:
    - asset: assets/fonts/Montserrat-Regular.ttf
      weight: 400
    - asset: assets/fonts/Montserrat-Medium.ttf
      weight: 500
    - asset: assets/fonts/Montserrat-SemiBold.ttf
      weight: 600
    - asset: assets/fonts/Montserrat-Bold.ttf
      weight: 700
